### ISSUE TITLE
לינק שבור+דיווח על פרסומות

### ISSUE THREAD

**Issue by xqgex** [AdBlockPlusIsrael/EasyListHebrew#36]
כשמנסים לדווח על פרסומות שלא הוסרו התוסף מפנה לכתובת:
https://github.com/AdBlockPlusIsrael/EasyListIsrael/issues
שמחזירה שגיאת 404

ובנוסף התוסף לא מסיר את הפרסומות של YNET

**Comment by EasyListIsrael** [comment]
about the 404 where do you see a this?
about ynet can you be more specific?
there is an issue that adblock takes a few seconds to load so if your home page is ynet it will have ads until you'll refresh the page

**Comment by xqgex** [comment]
![1](https://cloud.githubusercontent.com/assets/15404/5592589/ab9fd6cc-91df-11e4-8c11-32809dce4ba7.jpg)
![Uploading 2.jpg . . .]()
