### ISSUE TITLE
פרסומת שאינה מצונזרת

### ISSUE THREAD

**Issue by someone2222** [AdBlockPlusIsrael/EasyListHebrew#37]
בתוך כתבות האתר ווינט החל להופע חלון באמצע הכתבה שמוביל לציוצי טוויטר של כל מיני כתבים...
למשל כמו פה:
http://www.ynet.co.il/articles/0,7340,L-4617662,00.html

נשמח אם תוכלו לחסום את זה בעדכון הבא

**Comment by EasyListIsrael** [comment]
this is not an ad
you can block it yourself using this filter
||ynet.co.il/short/content/2014/YnetTwitterWidget
or add this list to adblock
https://easylist-downloads.adblockplus.org/fanboy-social.txt

**Comment by EasyListHebrewBarakSt** [comment]
This issue was moved to easylist/EasyListHebrew#37
