### ISSUE TITLE
חברת פרסום חדשה

### ISSUE THREAD

**Issue by ohadcn** [AdBlockPlusIsrael/EasyListHebrew#38]
דף הבית של החברה:
http://www.padv.co.il/
דוגמה לעמוד שהם מפרסמים בו:
http://www.inn.co.il/News/News.aspx/292133
מסנן:
||pigment-adv.co.il^$popup

**Comment by EasyListIsrael** [comment]
https://github.com/AdBlockPlusIsrael/EasyListHebrew/commit/42ebf62f89a1a63224c00f4e08437f9fa5ece81c

**Comment by ohadcn** [comment]
תודה על הטיפול המהיר!

**Comment by EasyListHebrewBarakSt** [comment]
This issue was moved to easylist/EasyListHebrew#38
