### ISSUE TITLE
This site contain unblockable ads

### ISSUE THREAD

**Issue by Omerz1** [AdBlockPlusIsrael/EasyListHebrew#39]
http://golda.iscool.co.il/%D7%93%D7%A3%D7%91%D7%99%D7%AA/tabid/448/language/he-IL/Default.aspx

and some other sites ... pleas figure it out, Thanks.

**Comment by EasyListIsrael** [comment]
i don't see any ads
please send a report
look here how
https://adblockplus.org/en/getting_started#problems

**Comment by EasyListHebrewBarakSt** [comment]
This issue was moved to easylist/EasyListHebrew#39
