### ISSUE TITLE
http://www.jobmaster.co.il/

### ISSUE THREAD

**Issue by someone900** [AdBlockPlusIsrael/EasyListHebrew#43]
http://www.jobmaster.co.il/

בתחתית האתר יש פרסומת:
"שוכר\משכיר דירה?"
עם הפניה לאתר KOMO.CO.IL

זו התמונה:
http://www.jobmaster.co.il/code/kot/imageurl.asp?num=5622

הפרסומת נחסמת ע"י AD MUNCHER 
אבל לא ע"י AD BLOCK

**Comment by EasyListHebrewBarakSt** [comment]
This issue was moved to easylist/EasyListHebrew#43
