### ISSUE TITLE
alljobs.co.il

### ISSUE THREAD

**Issue by someone900** [AdBlockPlusIsrael/EasyListHebrew#44]
באתר (דף ראשי) יש למעלה פרסומת
"חולם לעסוק בשיווק דיגיטלי"

לא הצלחתי לצרף צילום מסך.. 
זה מה שמופיע כשלחצתי על בדוק מרכיב באתר:
<a href="http://openx.alljobs.co.il/www/delivery/ck.php?oaparams=2__bannerid=6312" target="_blank" hidefocus="hidefocus" class="H150 W170 DisplayB MT10 IBlock" style="text-decoration:none;border:0px;outline: none"><img src="http://openx.alljobs.co.il/www/delivery/lg.php?bannerid=6312" width="0" height="0" style="display: none !important; visibility: hidden !important; opacity: 0 !important; background-position: 0px 0px;"></a>

**Comment by EasyListIsrael** [comment]
not sure this is an ad
this site offers you a job

**Comment by EasyListHebrewBarakSt** [comment]
This issue was moved to easylist/EasyListHebrew#44
