### ISSUE TITLE
Huge side banner on FXP

### ISSUE THREAD

**Issue by bmnot** [AdBlockPlusIsrael/EasyListHebrew#48]
Case in point: http://www.fxp.co.il/showthread.php?t=16224192
Seems almost... unblockable, for some reason. The selector keeps changing randomly. FYI

**Comment by EasyListHebrew** [comment]
​i don't see it please send report or attach image​

**Comment by bmnot** [comment]
![2015-06-06_091652](https://cloud.githubusercontent.com/assets/12750548/8018587/d5cb8ce4-0c2c-11e5-9923-b13b9efb5fae.png)
Huge flash banner on the right. It's sticky so it follows you when you scroll, and it's animated; super annoying.

**Comment by EasyListHebrewBarakSt** [comment]
This issue was moved to easylist/EasyListHebrew#48
