### ISSUE TITLE
ynet

### ISSUE THREAD

**Issue by Sctumsempra** [AdBlockPlusIsrael/EasyListHebrew#49]
שלום,
בעמודי המדורים של וואינט לא מופיע כל התוכן כשאדבלוק מופעל.
לדוגמה:
http://www.ynet.co.il/home/0,7340,L-544,00.html
http://www.ynet.co.il/home/0,7340,L-6,00.html
נסו להשהות את התוסף ותראו שהעמוד מכיל הרבה יותר כתבות.

**Comment by EasyListIsrael** [comment]
please provide print screens

**Comment by Sctumsempra** [comment]
With AdBlock:
http://i.imgur.com/gzaBg3u.jpg

Without AdBlock:
http://i.imgur.com/SsKdvjX.jpg

**Comment by EasyListIsrael** [comment]
i think it's an issue in your setup
1. check for updates
http://support.getadblock.com/kb/basic-troubleshooting/update-your-filters
are you using firefox?
if so
Click the ABP icon in top right corner
Select "Report issue on this page" 
post here the link

**Comment by Sctumsempra** [comment]
Thanks for responding.
I use Chrome with AdBlock, not ABP, and I don't have that option.

**Comment by EasyListIsrael** [comment]
still nothing
please upload print screen of 
press left click on adblock icon and select show list source (one above report an ad on this page)

**Comment by Sctumsempra** [comment]
http://imgur.com/a/Hpt7x
Thanks again,

**Comment by EasyListIsrael** [comment]
the problem is in your setup
i'm not sure where but i couldn't reproduce it
i suggest removing ad block and reinstalling or using adblock plus

**Comment by Sctumsempra** [comment]
Looks like reinstalling AdBlock fixed the problem (which is weird because I tried that before). Thanks and sorry for wasting your time :)

**Comment by EasyListHebrewBarakSt** [comment]
This issue was moved to easylist/EasyListHebrew#49
