### ISSUE TITLE
yad2 - anti ad blocking (reopen - #52)

### ISSUE THREAD

**Issue by tomprt** [AdBlockPlusIsrael/EasyListHebrew#53]
Hi, 
Same behavior as in #52.

script location changed to:
http://www.yad2.co.il/js-new/blockPirsum.js?v=1.1

`||yad2.co.il/js-new/blockAd.js` should be changed to:
`||yad2.co.il/js-new/blockPirsum.js`

Thanks.

**Comment by EasyListIsrael** [comment]
i can also add 
||wcdn.co.il/banners$popup
@@||fus.walla.co.il/$domain=yad2.co.il
what do you think?

**Comment by tomprt** [comment]
I've played with for a bit,
it does suppress the ad blocker message, but for me I there are banners on the right & bottom + there's a pop-up flicker when clicking an item.

limiting the scope of the whitelist - yields 0 ads & adblock check is passing.
`@@||fus.walla.co.il/ads/$domain=yad2.co.il`
even without `||wcdn.co.il/banners$popup`

so I think 
```
||yad2.co.il/js-new/blockPirsum.js
@@||fus.walla.co.il/ads/$domain=yad2.co.il
```
will hopefully work for a while.

**Comment by EasyListIsrael** [comment]
lets hope they won't start a war.
i don't mind that a small notice but disabling the site is to much

**Comment by EasyListHebrewBarakSt** [comment]
This issue was moved to easylist/EasyListHebrew#53
